### ISSUE TITLE
Sync Hierachy Slicer

### ISSUE THREAD

**Issue by alpinedelight** [liprec/azurebi-docs#18] opened 2018-09-26 08:05 UTC
The ability to be able to use sync slicers to allow hierarchy slicers across different report pages to stay consistent. I.e. change value on one page is kept on another page across the entire report.

Not an issue as such, but would really add value to this slicer.
Realised I'm not the first person to notice this :) 

[https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/33700477-hierarchy-slicer-sync](url)
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment] 2018-11-08 13:46
I will close this issue as it a duplicate of liprec/hierarchySlicer#22 is not document related.

**Closed by liprec** 2018-11-08 13:46 UTC
