### ISSUE TITLE
Will Hierarchy Slicer be submitted for certification by Microsoft? 

### ISSUE THREAD

**Issue by SOTCK** [liprec/azurebi-docs#62] opened 2019-10-18 15:19 UTC
I very much enjoy using the Hierarchy Slicer, but have a client who can only allow Marketplace custom visuals that are Microsoft certified. (i.e.  do not access external services or resources) Please advise whether the Hierarchy Slicer has been submitted for certification of will be in the near future.  

Thanks!

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment] 2019-10-21 09:17
At this moment the HierarchySlicer is not yet certified, but it will in the near future. At this moment I so not have any timelines when it will become certified.

**Comment by arenphansen** [comment] 2019-10-21 13:16
Hi liprec,

Just wanted to second SOTCK's request, this would be a huge help my organization also won't allow the use of this Hierarchy Slicer without it being Microsoft Certified. 

Can this please be expedited ASAP? 

Love the tool!!

**Comment by jkezzz** [comment] 2019-10-28 06:38
I'll second too. Our company just decided to block all other than MS certified visuals. Now we have to build all reports again with certified ones. There is no good substitute for e.g. Hierarchy Slicer.

**Comment by liprec** [comment] 2019-12-02 14:35
Closing as it is a duplicate of liprec/powerbi-hierarchySlicer#34

**Closed by liprec** 2019-12-02 14:35 UTC
Labels: HierarchySlicer
