### ISSUE TITLE
Issues related to Hierarchy Slicer in Power BI

### ISSUE THREAD

**Issue by NitinKangtani** [liprec/azurebi-docs#17] opened 2018-09-18 15:32 UTC
My name is Nitin Kangtani and I work for Meijer Inc., Grand Rapids, Michigan, USA. We are having some trouble with the Hierarchy slicer and needed to open a support issue. Can you or someone from your team help us?

Issue:

1.	Every time we are selecting a Fiscal year it is selecting the previous year’s end period as well. To explain this issue more, please find below the screenshot for the same.
![hierarchy slicer](https://user-images.githubusercontent.com/43381897/45698658-7e83e000-bb36-11e8-8e18-307a4ca1adf4.jpg)

2.	It is not letting us select multiple periods at a time in one fiscal year. Everytime we try to select multiple periods, it just selects 1 of them and does not allow to filter with the other periods.

We are seeking for help, as this is causing multiple issues with the reports. We tried to raise a ticket with Microsoft but they said that since it is a third party filter, they cannot help us.

Looking forward to your response as soon as possible.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by NitinKangtani** [comment] 2018-09-19 14:15
Hi Jan,

I am afraid that will not work as we are using a live connection and you will not have an access to the databases. Can anyone from your support team connect with me and see this issue by sharing my screen?

Thanks,
Nitin

**Comment by liprec** [comment] 2018-09-22 09:45
Hi @NitinKangtani, I suspect that this is caused by an issue that will be fixed by the upcoming release, which is next week (as I expected).
If it is not solved, I would rather have a PBIX file as I can debug easier to see what is causing this behavior.

Thanks, JP

**Comment by NitinKangtani** [comment] 2018-09-24 13:11
Thank you Jan! Can you please provide me an ETA for the release?

Thanks,
Nitin

**Comment by liprec** [comment] 2018-09-25 07:12
Looks like the new version is available to everyone.
Please clear your browser cache first to make sure that you are using the latest version.

**Closed** 2019-04-23 09:59 UTC
Labels: help wanted
