### ISSUE TITLE
Power BI Report Server : Box and Whiskers not working

### ISSUE THREAD

**Issue by ey1020park** [liprec/azurebi-docs#152] opened 2021-06-18 08:41 UTC
Hi,
I am working in a power bi report server environment. This custom visual is expressed well on the power bi desktop, but when uploaded to the power bi report server, the visual is not displayed and comes out white. I wonder if the visual can be used on the power bi report server.

![image](https://user-images.githubusercontent.com/66717685/122533305-5b2a4e80-d05c-11eb-923c-493da39cf801.png)

#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=4555c56c-3a13-42d3-a4d4-df34d7b4e455
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/box-and-whisker-chart.html

**Comment by erikmourits** [comment] 2021-06-30 07:47
I'm having the same issue. It looks to be browser specific. The chart renders in Firefox but not in Chrome.

**Comment by erikmourits** [comment] 2021-06-30 08:03
After some debugging the problem seems to be linked to cookies not having a correct SameSite attribute value (and maybe also not being secure). I was seeing a lot of 401 httpcode results on various *.js calls in Chrome. These calls were succeeding in Firefox.

**Comment by erikmourits** [comment] 2021-07-05 14:00
Our problem was (semi)fixed bij adding Samesite=None and Secure attributes into our custom cookie. We have another problem now when opening the chart that exists on a second tab/page. This chart renders correctly on the main page but after navigating to a second page we are seeing lots of 503 errors.

**Comment by liprec** [comment] 2021-07-05 14:04
Sorry for the late comment from my side: looks like this issue is related to the Power BI Report Service in combination with Chrome.
Are you all running the latest (patch) version of the Power BI Report Service?

**Comment by erikmourits** [comment] 2021-07-05 15:11
We are running version 1.10.7737.32652 (januari 2021) of PowerBI Report Server. So it looks like we're 1 version behind, as 1.11 is the latest version. I'm not seeing any changes relating to this bug in the changelog however: https://docs.microsoft.com/en-us/power-bi/report-server/changelog

**Comment by liprec** [comment] 2021-07-05 15:15
Best is then to raise a ticket with Microsoft as this looks to me as it is out of scope for my visual: the visual itself doesn't use any cookies or other tracking mechanism.

**Comment by erikmourits** [comment] 2021-07-05 15:28
Our original problem was related to a custom cookie we were using. That problem has been resolved on our side. This problem (http 503 errors) seems unrelated.

**Comment by ey1020park** [comment] 2021-07-06 00:38
> Our problem was (semi)fixed bij adding Samesite=None and Secure attributes into our custom cookie.

@erikmourits 
Can you share how to fix it? Still I can't solve the issue.

Somebody advised to add attribute like below on web.config but it didn't work to me.
<forms loginUrl="logon.aspx" name="sqlAuthCookie" timeout="60" path="/" cookieSameSite="None"></forms>
https://community.powerbi.com/t5/Report-Server/Power-Bi-Report-Server-Custom-Text-Filter-visual-401-error-forms/m-p/947334

**Comment by erikmourits** [comment] 2021-07-06 08:00
> > Our problem was (semi)fixed bij adding Samesite=None and Secure attributes into our custom cookie.
> 
> @erikmourits
> Can you share how to fix it? Still I can't solve the issue.

I'm assuming you're running custom authentication.
`<httpCookies sameSite="None" requireSSL="true" httpOnlyCookies="true" />`
Adding that to the web.config worked for us.

**Comment by liprec** [comment] 2021-07-06 08:09
Hi @erikmourits,

Thanks for the additional context about the custom authentication. Now all make sense in the case of the cookies and the changes that were made regarding SameSite cookies. For more information take a look at e.g.: [https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-handle-samesite-cookie-changes-chrome-browser?tabs=dotnet](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-handle-samesite-cookie-changes-chrome-browser?tabs=dotnet&WT.mc_id=DP-MVP-5003419)

**Comment by erikmourits** [comment] 2021-07-06 08:13
@liprec We're going to try and narrow down where the problem is originating from. The standard charts are all working but still getting 503 errors (on js/css files) when loading the box and whiskers chart. It is a weird problem because the request for the js/css files succeed the first time, but fail when switching to an other page/tab. The request that is done is exactly the same (url, headers, etc) for both requests.

**Closed as completed** 2021-09-12 12:16 UTC
Labels: wontfix
