### ISSUE TITLE
The HierarchySlicer is not working in Mozilla Firefox, but it is working fine in other browser like chrome.

### ISSUE THREAD

**Issue by Vandana-isd** [liprec/azurebi-docs#122] opened 2020-07-11 01:17 UTC
*Start issue here*

Issue : We found that "HierarchySlicer" is not working and not visible in Power BI reports opened in firefox browser . But at the same time, we are able to see the HierarchySlicer in other browser like chrome, edge.

As workaround, we tried installing latest version of firefox , but still the slicer is not appearing in report. We also tried installing latest power bi desktop version, but still it did not resolved the issue.

can you please suggest how this can be resolved?

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment] 2020-07-16 08:06
Closed as duplicate of #118

**Closed by liprec** 2020-07-16 08:06 UTC
