### ISSUE TITLE
Can't sort by other field in the slicer

### ISSUE THREAD

**Issue by yukabest** [liprec/azurebi-docs#115] opened 2020-07-02 19:27 UTC
*Start issue here*

I used this slicer to be our org structure in our Power BI dashboard
It have many "levels" and the last level I put "order" so the org structure can be sorted by the "order" field.

I didn't make any change to the slicer and last week all of a sudden the org structure is sorted by "level name" not "order" field any more. I checked the "... sort by" and it still shows sort by "order" field. 

Is there anything recently got changed? Could you please let me know how to make the sort works? Thanks 
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment] 2020-07-03 08:42
Hi @yukabest,

Thanks for your feedback and sorry for the inconvenience. The internal structure of the slicer has changed to accommodate the report page feature and that is the root cause of why this sorting behavior is not working anymore.

But if I test it myself sorting based on the `values` is still working. Can you try reapplying the sort to see if it works?
Or you can take a look at the 'Sort by column' option to apply custom sorting: https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column

**Comment by yukabest** [comment] 2020-07-03 11:18
Hi Jan,

Thanks for your quick response.
I already tried to sort by other fields. I also tried to sort in table directly. Neither of the solution works.

Here is an example. My org has maximum 6 levels (some departments have less levels) - see my first screen shot
In order to sort by a different field and not show it, I put level 07 which is empty
Therefore, visorder (the field after level 7) won't be displayed either

It was working before June. I was able to display the org by visorder meanwhile make visorder invisible.
But from last month, it doesn't sort by visorder any more.

Any idea how I can get this fixed? Pretty much all my dashboards are not functional now.

Thanks.

[cid:fca95db7-707f-4898-b0b8-cb302b20a894]

[cid:b12d573a-c8e8-4903-9fe5-7c46b8186c1d]
Regards,

Yuka Jin M.A.Sc
Senior Consultant
SAP?? Business One, All-in-One, ByDesign
CPA PCP
yukajin@live.com<mailto:yukajin@live.com>
Tel: 403.519.9391[cid:302b1bb5-9d02-4967-871f-fd3dfcc5ad8c]


________________________________

**Comment by liprec** [comment] 2020-07-03 11:40
Sorry but apparently the email functionality disables the screenshots.
Can you either upload them here or maybe you can share a PBIX file with the screenshots and send them to mail@datascenarios.nl?

**Comment by yukabest** [comment] 2020-07-03 15:27
Thanks Jan. Just sent the pbi file to the email you mentioned
Please let me know if you want more clarification from me

Regards,

Yuka Jin
Tel: 403.519.9391

On Jul 3, 2020, at 5:40 AM, Jan Pieter Posthuma <notifications@github.com> wrote:

﻿

Sorry but apparently the email functionality disables the screenshots.
Can you either upload them here or maybe you can share a PBIX file with the screenshots and send them to mail@datascenarios.nl<mailto:mail@datascenarios.nl>?

**Comment by liprec** [comment] 2020-07-07 11:20
Closing this item as we solved this offline.

**Closed by liprec** 2020-07-07 11:20 UTC
Labels: HierarchySlicer, question
