### ISSUE TITLE
Visual Not Working on Firefox

### ISSUE THREAD

**Issue by tcarpi-ey** [liprec/azurebi-docs#119] opened 2020-07-09 12:47 UTC
Hello, I have problem in using this visual on Firefox with hierarchies. It looks like it is not compatible and the visual is Blank (see photo).
Everything works fine on Chrome.

![image](https://user-images.githubusercontent.com/46570355/87041732-f41cdc80-c1f2-11ea-819b-72c7e23442c2.png)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=2380fb48-08d2-44bc-aaa2-2decb8eeed18
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/index.html

**Comment by liprec** [comment] 2020-07-16 08:06
Closed as duplicate of #118

**Closed by liprec** 2020-07-16 08:06 UTC
